# Generated by Django 3.1.6 on 2021-02-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
