# Generated by Django 3.1.6 on 2021-02-19 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210219_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('1a6d072d-bf62-4137-9516-f975b1bdf527'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
