# Generated by Django 3.1.6 on 2021-02-24 18:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210219_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('c80f9f0b-5c5c-4112-a92b-4931e7cbdce0'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
