# Generated by Django 3.1.6 on 2021-04-14 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210224_1526'),
        ('core', '0007_auto_20210413_1426'),
    ]

    operations = [
    ]
