# Generated by Django 3.1.6 on 2021-04-19 17:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20210414_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contract_types',
            field=models.ManyToManyField(to='core.ContractType'),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('a95576cd-999c-49ca-a45f-c6dcef592044'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
