# Generated by Django 3.1.6 on 2021-11-03 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210419_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('f93907a5-fec1-4874-93e9-9b145a2f8d2f'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
