# Generated by Django 3.1.6 on 2022-01-29 04:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220129_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('ebf9d1cd-cb39-489d-bf7a-6c4a54dc9d27'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
