# Generated by Django 3.1.6 on 2022-02-22 23:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220129_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contract_types',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contract_types',
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('a8879cdb-b4eb-428a-9796-971b34ced307'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
