# Generated by Django 3.1.6 on 2022-02-23 22:38

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_auto_20220222_2014"),
    ]

    operations = [
        migrations.AddField(
            model_name="local",
            name="city",
            field=models.CharField(default=" ", max_length=85),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="local",
            name="cood_x",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="local",
            name="cood_y",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="user",
            name="public_id",
            field=models.CharField(
                default=uuid.UUID("04607b61-c4de-4939-8ace-c17a69600b47"),
                help_text="Random sequence to be used as a public identifier.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
