# Generated by Django 3.1.6 on 2022-02-24 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20220223_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='cood_x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='local',
            old_name='cood_y',
            new_name='longitude',
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('2591c893-20f9-4d3b-a30d-56512529093c'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
