# Generated by Django 3.1.6 on 2022-02-24 22:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220224_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('c0980b1d-2fb4-4d96-adea-fe1bbdeec7d1'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
