# Generated by Django 3.1.6 on 2022-02-24 22:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220224_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('a442f05c-f21f-4d97-b088-e15bdf126ed8'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
