# Generated by Django 3.1.6 on 2022-02-24 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220224_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('1adaa821-1a2a-42d5-8b45-5814403506dc'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
