# Generated by Django 3.1.6 on 2022-02-24 23:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20220224_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('615e80aa-71f7-4e5e-ac95-3e12717f471c'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
