# Generated by Django 5.0.4 on 2024-08-14 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_company_id_alter_contracttype_id_alter_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('36e77d56-664a-44f8-9880-bc83106f4332'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job'),
        ),
    ]
