# Generated by Django 5.0.4 on 2024-08-26 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_user_public_id_alter_userjob_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.CharField(default=uuid.UUID('37ad5591-933a-4491-a481-67bc28998879'), help_text='Random sequence to be used as a public identifier.', max_length=255, unique=True),
        ),
    ]
