# Generated by Django 5.0.4 on 2024-09-29 18:14

import backend.core.models.user
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_reset_code_alter_user_public_id'),
        ('files', '0002_alter_document_id_alter_image_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', backend.core.models.user.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='educatiol_Level',
            field=models.IntegerField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensino Médio'), (3, 'Ensino Superior'), (4, 'Pós-Graduação'), (5, 'Mestrado'), (6, 'Doutorado')], default=2),
        ),
        migrations.AddField(
            model_name='job',
            name='image_job',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.image'),
        ),
        migrations.AddField(
            model_name='job',
            name='isPcd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='isTravel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('8d98c8fe-027f-48d7-90d6-9264f8b349ee'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Sequência aleatória usada como identificador público.', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='core.benefit'),
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.category'),
        ),
    ]
