# Generated by Django 5.0.4 on 2024-09-29 18:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_benefit_category_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('16a13850-5e25-4a6a-997c-df86e8e9afe1'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
