# Generated by Django 5.0.4 on 2024-09-29 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_user_passage_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('65605604-a233-4988-8aea-592848550c5a'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
