# Generated by Django 5.1.1 on 2024-10-07 17:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_user_passage_id_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='isExpired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('2d6dbe73-2fb9-461a-918b-8a74c1b4d9c4'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
