# Generated by Django 5.1.1 on 2024-10-07 18:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_local_latitude_alter_local_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('58d7b99e-7d8c-4b74-8ea7-3a244fdf8670'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
