# Generated by Django 5.1.1 on 2024-11-12 19:05

import backend.core.models.company
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_user_passage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cidade',
            field=models.CharField(blank=True, help_text='Digite a cidade.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='endereco',
            field=models.CharField(blank=True, help_text='Digite o endereço completo.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fantasy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='telefone',
            field=models.CharField(blank=True, help_text='Digite um número de telefone válido, incluindo o código do país, se necessário.', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve ter entre 9 e 15 dígitos, podendo incluir o código do país.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(help_text='Digite um CNPJ válido com 14 dígitos.', max_length=14, unique=True, validators=[backend.core.models.company.validate_cnpj]),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(help_text='Digite um email válido.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('7dd0b3b0-5e24-459a-a0f4-c310bed28845'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
