# Generated by Django 5.1.1 on 2024-11-12 19:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_company_cidade_company_endereco_company_fantasy_name_and_more'),
        ('files', '0002_alter_document_id_alter_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='company',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='job',
            name='local',
        ),
        migrations.AddField(
            model_name='company',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.local'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.image'),
        ),
        migrations.AddField(
            model_name='company',
            name='pessoa_de_contato',
            field=models.CharField(blank=True, help_text='Digite o nome completo da pessoa de contato na empresa.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ramo',
            field=models.CharField(blank=True, choices=[('TEC', 'Tecnologia'), ('FIN', 'Financeiro'), ('SAU', 'Saúde'), ('EDU', 'Educação'), ('COM', 'Comércio'), ('OUT', 'Outro')], help_text='Escolha o ramo de atuação da empresa.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('836cf5dd-224f-4a54-9231-d641b9f8546b'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
