# Generated by Django 5.1.1 on 2024-11-14 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_company_cidade_remove_company_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='core.job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('0a5c8c78-5c71-49b6-84b3-d64a3beb9658'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
