# Generated by Django 5.1.1 on 2024-11-13 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_company_cidade_remove_company_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='core.job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('63f8d87b-9d84-437c-ab9c-fbc609831606'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
