# Generated by Django 5.1.1 on 2024-11-14 16:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_user_jobs_alter_user_passage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('a7cc8545-3008-4e09-95b9-62cc128a3db8'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
        migrations.DeleteModel(
            name='UserJob',
        ),
    ]
