# Generated by Django 5.1.1 on 2024-11-13 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_job_company_company_job_alter_user_passage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default=uuid.UUID('fcb5dd3f-da3a-4c35-a42d-0bddad583e5d'), help_text='Digite uma senha segura.', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('726d50a2-2270-4a09-91fb-b58c8d02021d'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
