# Generated by Django 5.1.1 on 2024-11-13 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_company_password_alter_user_passage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(help_text='Digite uma senha segura.', max_length=128),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('7b1ef3cd-22fa-4a85-9ec4-64cfbed08fce'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
