# Generated by Django 5.1.1 on 2024-11-14 17:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_job_company_company_job_alter_user_passage_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobs',
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('8e47f343-ad75-40b6-839d-faf85bf38425'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pedente'), (2, 'Rejeitado'), (3, 'Aceito')], default=1)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
