# Generated by Django 5.1.1 on 2024-11-14 17:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_user_jobs_alter_user_passage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.job'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('add8e66c-941f-4437-9e62-fd3b175251e6'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
