# Generated by Django 5.1.1 on 2024-11-14 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_jobapplication_job_alter_user_passage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='educatiol_Level',
            new_name='education_level',
        ),
        migrations.AddField(
            model_name='job',
            name='isClosed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='max_candidates',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('10e1a250-bbbd-4a4f-8bcf-9ddef693876d'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
