# Generated by Django 5.1.1 on 2024-11-14 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_rename_educatiol_level_job_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='selected_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Rejeitado'), (3, 'Selecionado')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('9111103b-e732-411c-81b6-72abfc1a726c'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
