# Generated by Django 5.1.1 on 2024-11-15 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_job_selected_user_jobapplication_is_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pendente'), (2, 'Rejeitado'), (3, 'Selecionado'), (4, 'Não selecionado')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('60b60b41-70e9-41f5-9714-7605e674b292'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
