# Generated by Django 5.1.1 on 2025-01-03 19:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_alter_jobapplication_status_alter_user_passage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comorbidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.IntegerField(choices=[(1, 'Ensino Fundamental'), (2, 'Ensino Médio'), (3, 'Ensino Superior'), (4, 'Pós-Graduação'), (5, 'Mestrado'), (6, 'Doutorado')], default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='isPcd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isTravel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.local'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('0fd96291-6d3b-481c-99e7-9e850f7887b4'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
