# Generated by Django 5.1.1 on 2025-01-06 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_user_comorbidade_user_education_level_user_ispcd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='defaultpassword', help_text='Senha da empresa (hash).', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('1d8880aa-c86e-48f4-8ff3-331fbb79a02a'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
