# Generated by Django 5.1.1 on 2025-01-06 19:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_company_password_alter_user_passage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('1c1bbe2a-14d1-41f8-be84-3fd2c32e49c6'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
