# Generated by Django 5.1.1 on 2025-01-06 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_company_reset_code_alter_user_passage_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='job',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='passage_id',
            field=models.UUIDField(default=uuid.UUID('af57db34-d3ba-4b1e-831c-047bea2f25e2'), help_text='Identificador de passagem', unique=True, verbose_name='ID de passagem'),
        ),
    ]
