# Generated by Django 5.1.1 on 2025-01-10 15:09

import backend.core.models.user
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_company_job_job_company_alter_user_passage_id'),
        ('files', '0002_alter_document_id_alter_image_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='comorbidade',
            new_name='fantasy_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isPcd',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isTravel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_code',
        ),
        migrations.AddField(
            model_name='user',
            name='cnpj',
            field=models.CharField(blank=True, help_text='Digite um CNPJ válido com 14 dígitos.', max_length=14, null=True, unique=True, validators=[backend.core.models.user.validate_cnpj]),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_logos', to='files.image'),
        ),
        migrations.AddField(
            model_name='user',
            name='pessoa_de_contato',
            field=models.CharField(blank=True, help_text='Nome completo da pessoa de contato na empresa.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ramo',
            field=models.CharField(blank=True, help_text='Ramo de atuação da empresa.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STANDARD', 'Usuário Padrão'), ('COMPANY', 'Empresa')], default='STANDARD', help_text='Define se o usuário é padrão ou uma empresa.', max_length=8),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.image'),
        ),
        migrations.AlterField(
            model_name='user',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.local'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=31, validators=[django.core.validators.RegexValidator(message='O telefone deve ter entre 9 e 15 dígitos, podendo incluir o código do país.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
