# Generated by Django 5.1.1 on 2025-01-10 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rename_comorbidade_user_fantasy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=31, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve ter entre 9 e 15 dígitos, podendo incluir o código do país.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
