# Generated by Django 5.1.1 on 2025-01-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='category',
            new_name='ramo',
        ),
    ]
