# Generated by Django 5.1.1 on 2025-01-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_rename_category_job_ramo'),
        ('files', '0002_alter_document_id_alter_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comorbidade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='curriculo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='files.document'),
        ),
    ]
