# Generated by Django 5.1.1 on 2025-01-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_user_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
