# Generated by Django 5.1.1 on 2025-05-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_user_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='job',
            name='isClosed',
        ),
        migrations.RemoveField(
            model_name='job',
            name='isPcd',
        ),
        migrations.RemoveField(
            model_name='job',
            name='max_candidates',
        ),
        migrations.RemoveField(
            model_name='job',
            name='ramo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='selected_user',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='cityState',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='contract_type',
            field=models.IntegerField(choices=[(1, 'CLT'), (2, 'Estagiário')], default=2),
        ),
        migrations.AddField(
            model_name='job',
            name='details',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='job',
            name='wage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
