# Generated by Django 5.1.1 on 2025-05-08 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_remove_job_description_remove_job_education_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='cityState',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
