# Generated by Django 5.1.1 on 2025-05-08 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_job_state_alter_job_address_alter_job_citystate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='core.state'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=50, null=True)),
                ('state_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_city', to='core.state')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city', to='core.city'),
            preserve_default=False,
        ),
    ]
