# Generated by Django 5.1.1 on 2025-05-09 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_job_state_city_job_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='local',
        ),
        migrations.RemoveField(
            model_name='company',
            name='password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pessoa_de_contato',
        ),
        migrations.RemoveField(
            model_name='company',
            name='ramo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cityState',
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cityComp', to='core.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stateComp', to='core.state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='contract_type',
            field=models.IntegerField(choices=[(1, 'CLT'), (2, 'Estagiário'), (3, 'PJ'), (4, 'Freelancer')], default=2),
        ),
    ]
