# Generated by Django 5.1.1 on 2025-05-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_company_local_remove_company_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fantasy_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='local',
        ),
        migrations.RemoveField(
            model_name='user',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pessoa_de_contato',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ramo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='comorbidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
