# Generated by Django 5.1.1 on 2025-05-12 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_user_address_user_city_user_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cityUser', to='core.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stateUser', to='core.state'),
        ),
    ]
