# Generated by Django 5.1.1 on 2025-05-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_user_city_alter_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='abbreviation',
        ),
    ]
