# Generated by Django 5.1.1 on 2025-05-13 10:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_city_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='formation',
            field=models.IntegerField(choices=[(1, 'Fundamental Incompleto '), (2, 'Fundamental Completo'), (3, 'Médio Incompleto'), (4, 'Médio Completo'), (5, 'Superior Incompleto'), (6, 'Superior Completo'), (7, 'Mestrado'), (8, 'Doutorado')], default=4),
        ),
        migrations.AddField(
            model_name='user',
            name='formationPlace',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=31, null=True, validators=[django.core.validators.RegexValidator(message='O telefone deve ter entre 9 e 15 dígitos, podendo incluir o código do país.', regex='^\\+?1?\\d{9,1 5}$')]),
        ),
    ]
