# Generated by Django 5.1.1 on 2025-05-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_rename_formationplace_user_formation_place_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContractType',
        ),
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=models.ManyToManyField(blank=True, related_name='benefits', to='core.benefit'),
        ),
    ]
