# Generated by Django 5.1.1 on 2025-05-26 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_delete_contracttype_alter_job_benefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateField(default=datetime.date(2025, 6, 25)),
        ),
    ]
