# Generated by Django 5.1.1 on 2025-05-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_job_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about',
            field=models.TextField(default='Esta empresa não possuí descrição ainda.', max_length=1500),
        ),
    ]
